import { MESSAGE } from "types/message";

export enum LIFE_CYCLE {
  FRONTEND_READY = "FRONTEND_READY",
  REGISTER_DEVTOOL = "REGISTER_DEVTOOL",
  PROXY_READY = "PROXY_READY",
}

export type LIFE_CYCLE_TYPE_DATA = {
  [LIFE_CYCLE.FRONTEND_READY]: MESSAGE;
  [LIFE_CYCLE.REGISTER_DEVTOOL]: MESSAGE;
  [LIFE_CYCLE.PROXY_READY]: MESSAGE;
};
